### PR TITLE
Added a links array in Entity which will automatically be filled

### PR DESCRIPTION
**Pull request by fyfey**
The trait already looks for the property and will copy the array over
from the API results

### CODE REVIEW

**Comment by CristianGiordano** [comment]
Think we need an accessor for it though :)

**Comment by fyfey** [comment]
I was using toArray to access the data.

I'm creating a SugarCRM integration, and this works perfectly to copy it to Sugar's entity object. I will happily add a getLinks method though.

**Comment by fyfey** [comment]
I've added an accessor for links.

The links param can stay in when posting as it's a valid request.

**Comment by CristianGiordano** [comment]
Thanks :+1:

**Pull request merged**
